sudo: false
language: cpp
os:
- linux
- osx
compiler:
- gcc
dist: bionic
matrix:
  fast_finish: true
env:
  matrix:
  - BUILD_TYPE="Release"
addons:
  apt:
    packages:
    - build-essential
    - libbluetooth-dev
    - libcurl4-gnutls-dev
    - libfreetype6-dev
    - libgl1-mesa-dev
    - libjpeg-dev
    - libpng-dev
    - libwxgtk3.0-dev
    - pkg-config
    - zlib1g-dev
    - libasound2-dev
before_script:
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update && brew bundle; fi
script:
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then python scons/scons.py -j3; fi
- if [[ "$TRAVIS_OS_NAME" != "osx" ]]; then python scons/scons.py -j3; fi
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then python scons/scons.py install; fi
before_deploy:
- zip -r build.zip .
deploy:
  provider: releases
  api_key:
    secure: $API_KEY
  file: build.zip
  on:
    repo: ariamaestosa/ariamaestosa
    branch: TravisRelease
