sudo: false
language: cpp
os:
- linux
- osx
compiler:
- gcc
dist: bionic
matrix:
  fast_finish: true
env:
  matrix:
  - BUILD_TYPE="Release"
addons:
  apt:
    packages:
    - build-essential
    - libbluetooth-dev
    - libcurl4-gnutls-dev
    - libfreetype6-dev
    - libgl1-mesa-dev
    - libjpeg-dev
    - libpng-dev
    - libwxgtk3.0-dev
    - pkg-config
    - zlib1g-dev
    - libasound2-dev
before_script:
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update && brew bundle; fi
script:
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then python scons/scons.py -j3; fi
- if [[ "$TRAVIS_OS_NAME" != "osx" ]]; then python scons/scons.py -j3; fi
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then ./package_osx.sh; fi
before_deploy:
- zip -r "build_$TRAVIS_OS_NAME.zip" .
deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: ghqx410rraSUAV1pcynyNnt4rUFlMOnPNEexhRmC48ugbVR4CyKoXdpOGy8pfkDS4EMw7Wh3OlzBwjG8FP9Ne5T7n+DzwOBaNGZvYKkrK5iPaIU1D6TPrhG7KZvwHRLSh8zGE35/748hSaqnHyNhXMP2PujApzrCS7dlIuY7DF+QwkIBfmlgd0CyqBT8KtUk6arUJ9itbTKjSlhu9r8Ox5nRoaVRLMe/J5filfQjbDaGU3rIUNQ8DQrO1d+9Xoy4S276eXcBcwLMinjCS3DZMQa0enmptNFSS5Td8DebVn/Xz2tx0gbLxYTYhXIbtOXfPtKbdAqWGaZKhoujtVppoy+bbP2lAmtkJxLCWyrMSKBOGsxLSS9ECngyt6bitYU1EKjOTqxIrr6D1VedswLsvEYvZIFAGgCfN7MMkJjgpf8x5Ns7H2aocLqujjxO2SJY31faq2Ymhs5s5UEKvjXGeVpMki+eLvFisySoWYNCIcCzDPzTtCcVYSurEwYj9trqM1TqRLKwIDV+G77/p7cdTS5UzQvS0oV2NbNohPlqiJXT9uA2XToTEEr4Rt0PUutxUnWNQQKVBU5vJjd0ry228EwsCoI5Zpk4DIrFSdEDa2vgQ0sTzzjn61lrKCrumVtjeDtfF2dkiWPXgqR0S793wwBEjAkWJnyEDYZpunrz1D0=
  file: "build_$TRAVIS_OS_NAME.zip"
  on:
    repo: ariamaestosa/ariamaestosa
    branch: TravisRelease
