document.write('        </td>');
document.write('        <td style="width: 250px; background-image:url(\'background.png\'); background-repeat:repeat-y; margin: 0px; padding: 0px;">');
document.write('        </td>');
document.write('    </tr>');
    
document.write('    <tr style="margin: 0px; padding: 0px;">');
document.write('        <td style="width: 250px; background-image:url(\'backgroundleft.png\'); background-repeat:repeat-y; margin: 0px; padding: 0px;">');
document.write('        </td>');
document.write('        <td style="background-color:#628DC2;">');
document.write('            <br/>');
document.write('            <center>');
document.write('                <span class="bottom">Aria Maestosa is released under the GNU GPL 2 license<br/>We are freely hosted by <a href="http://sourceforge.net">sourceforge.net</a></span>');
document.write('                <br/>');
document.write('                <br/>');
document.write('            </center>');
document.write('        </td>');
document.write('        <td style="width: 250px; background-image:url(\'background.png\'); background-repeat:repeat-y; margin: 0px; padding: 0px;">');
document.write('        </td>');
document.write('    </tr>');
document.write('</table>');